{{- $values := $.Values }}
{{- if $values.ingress.enabled }}
{{- $fullName := include "hasher-matcher-actioner.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hasher-matcher-actioner.labels" . | nindent 4 }}
  {{- with $values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $values.ingress.className }}
  {{- with $values.ingress.tls }}
  tls:
    {{- range . }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ $values.ingress.host }}
      http:
        paths: 
          {{- range $roleName, $roleCfg := $values.roleGroups }}
          {{- with $roleCfg.ingressRule }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $roleName }}
                port:
                  name: http
          {{- end }}
          {{- end }}
{{ end }}