apiVersion: v1
kind: ConfigMap
metadata:
  name: migration
  labels:
    {{- include "hasher-matcher-actioner.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    {{- if .Values.migration.hook.enabled }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
    helm.sh/hook-delete-policy: before-hook-creation
    {{- end }}
data:
  omm_config.py: |
    import os

    from OpenMediaMatch.storage.postgres.impl import DefaultOMMStore

    DBHOST = os.environ["POSTGRES_HOST"]
    DBPORT = os.environ["POSTGRES_PORT"]
    DBNAME = os.environ["POSTGRES_DB"]
    DBUSER = os.environ["POSTGRES_USER"]
    DBPASS = os.environ["POSTGRES_PASSWORD"]
    
    DATABASE_URI = f"postgresql+psycopg2://{DBUSER}:{DBPASS}@{DBHOST}:{DBPORT}/{DBNAME}"

    PRODUCTION = True
