{{- $values := $.Values }}
{{- range $roleName, $roleCfg := .Values.roleGroups }}
{{- if (and $roleCfg.enabled $roleCfg.pdb) }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $roleName }}
  labels:
    {{- include "hasher-matcher-actioner.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "hasher-matcher-actioner.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $roleName }}
  {{- with $roleCfg.pdb.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with $roleCfg.pdb.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
{{- end }}
{{- end }}