{{ $values := $.Values }}
{{- range $roleName, $roleCfg := .Values.roleGroups -}}
{{- if $roleCfg.enabled -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $roleName }}
  labels:
    {{- include "hasher-matcher-actioner.labels" $ | nindent 4 }}
spec:
  replicas: {{ $roleCfg.replicas | default 1 }}
  strategy:
    {{- $effectiveStrategy := coalesce $roleCfg.strategy $values.roleDefaults.strategy }}
    {{- with $effectiveStrategy }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  revisionHistoryLimit: {{ coalesce $roleCfg.revisionHistoryLimit $values.roleDefaults.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "hasher-matcher-actioner.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: {{ $roleName }}
  template:
    metadata:
      labels:
        {{- include "hasher-matcher-actioner.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: {{ $roleName }}
        {{- with (merge $values.podLabels (default (dict) $roleCfg.labels)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with $roleCfg.config }}
        checksum/config: {{ (tpl . $) | sha256sum }}
        {{- end }}
        {{- with (merge $values.podAnnotations (default (dict) $roleCfg.annotations)) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "hasher-matcher-actioner.serviceAccountName" $ }}
      {{- with $values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $roleName }}
          image: "{{ $values.image.repository }}:{{ $values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $values.image.pullPolicy }}
          {{- with $values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12  }}
          {{- end }}
          command:
            - "gunicorn"
            - "--bind"
            - "0.0.0.0:5000"
            - "OpenMediaMatch.app:create_app()"
          env:
            - name: MIGRATION_COMMAND
              value: "0"
            - name: PRODUCTION
              value: "True"
            - name: OMM_CONFIG
              value: /config/omm_config.py
            {{- include "hasher-matcher-actioner.databaseEnv" $ | nindent 12 }}
            {{- with $roleCfg.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if $roleCfg.config }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          {{- end }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /status
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          {{- with $values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $roleCfg.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if $roleCfg.config }}
      volumes:
        - name: config
          configMap:
            name: {{ $roleName }}
      {{- end }}
      {{- with $values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $values.roleAffinityTemplate }}
      affinity:
        {{- (tpl . (dict "Values" (dict "roleName" $roleName) "Template" (dict "Name" "" "BasePath" ""))) | nindent 8 }}
      {{- end }}
      {{- with $values.roleTopologySpreadConstraintsTemplate }}
      topologySpreadConstraints:
        {{- (tpl . (dict "Values" (dict "roleName" $roleName) "Template" (dict "Name" "" "BasePath" ""))) | nindent 8 }}
      {{- end }}
      {{- with $values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end -}}
{{ end -}}