{{- if .Values.secret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "hasher-matcher-actioner.labels" $ | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.database.password | b64enc }}
{{- end }}
