apiVersion: v2
name: hasher-matcher-actioner
description: A Helm chart for ThreatExchange/hasher-matcher-actioner
type: application
version: 0.1.0
appVersion: "1.0.17"
dependencies:
  - name: postgresql
    version: 16.7.15
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nginx
    version: 21.0.6
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
